export const WPLACE_COLORS = [
  { "code": "#000000", "name": "black", "locked": false },
  { "code": "#3c3c3c", "name": "dark gray", "locked": false },
  { "code": "#787878", "name": "gray", "locked": false },
  { "code": "#d2d2d2", "name": "light gray", "locked": false },
  { "code": "#ffffff", "name": "white", "locked": false },
  { "code": "#600018", "name": "deep red", "locked": false },
  { "code": "#ed1c24", "name": "red", "locked": false },
  { "code": "#ff7f27", "name": "orange", "locked": false },
  { "code": "#f6aa09", "name": "gold", "locked": false },
  { "code": "#f9dd3b", "name": "yellow", "locked": false },
  { "code": "#fffabc", "name": "light yellow", "locked": false },
  { "code": "#0eb968", "name": "dark green", "locked": false },
  { "code": "#13e67b", "name": "green", "locked": false },
  { "code": "#87ff5e", "name": "light green", "locked": false },
  { "code": "#0c816e", "name": "dark teal", "locked": false },
  { "code": "#10aea6", "name": "teal", "locked": false },
  { "code": "#13e1be", "name": "light teal", "locked": false },
  { "code": "#28509e", "name": "dark blue", "locked": false },
  { "code": "#4093e4", "name": "blue", "locked": false },
  { "code": "#60f7f2", "name": "cyan", "locked": false },
  { "code": "#6b50f6", "name": "indigo", "locked": false },
  { "code": "#99b1fb", "name": "light indigo", "locked": false },
  { "code": "#780c99", "name": "dark purple", "locked": false },
  { "code": "#aa38b9", "name": "purple", "locked": false },
  { "code": "#e09ff9", "name": "light purple", "locked": false },
  { "code": "#cb007a", "name": "dark pink", "locked": false },
  { "code": "#ec1f80", "name": "pink", "locked": false },
  { "code": "#f38da9", "name": "light pink", "locked": false },
  { "code": "#684634", "name": "dark brown", "locked": false },
  { "code": "#95682a", "name": "brown", "locked": false },
  { "code": "#f8b277", "name": "beige", "locked": false },
  { "code": "#aaaaaa", "name": "medium gray", "locked": true },
  { "code": "#a50e1e", "name": "dark red", "locked": true },
  { "code": "#fa8072", "name": "light red", "locked": true },
  { "code": "#e45c1a", "name": "dark orange", "locked": true },
  { "code": "#9c8431", "name": "dark goldenrod", "locked": true },
  { "code": "#c0a830", "name": "goldenrod", "locked": true },
  { "code": "#e8d45f", "name": "light goldenrod", "locked": true },
  { "code": "#4a6b3a", "name": "dark olive", "locked": true },
  { "code": "#5a944a", "name": "olive", "locked": true },
  { "code": "#84c573", "name": "light olive", "locked": true },
  { "code": "#0f799f", "name": "dark cyan", "locked": true },
  { "code": "#bbfaf2", "name": "light cyan", "locked": true },
  { "code": "#7cc5fc", "name": "light blue", "locked": true },
  { "code": "#4d31b8", "name": "dark indigo", "locked": true },
  { "code": "#4a4284", "name": "dark slate blue", "locked": true },
  { "code": "#7a71c4", "name": "slate blue", "locked": true },
  { "code": "#b5aef1", "name": "light slate blue", "locked": true },
  { "code": "#9b5249", "name": "dark peach", "locked": true },
  { "code": "#d18078", "name": "peach", "locked": true },
  { "code": "#fab6a4", "name": "light peach", "locked": true },
  { "code": "#dba463", "name": "light brown", "locked": true },
  { "code": "#7b6352", "name": "dark tan", "locked": true },
  { "code": "#9c846b", "name": "tan", "locked": true },
  { "code": "#d6b594", "name": "light tan", "locked": true },
  { "code": "#d18051", "name": "dark beige", "locked": true },
  { "code": "#ffc5a5", "name": "light beige", "locked": true },
  { "code": "#6d643f", "name": "dark stone", "locked": true },
  { "code": "#948c6b", "name": "stone", "locked": true },
  { "code": "#cdc59e", "name": "light stone", "locked": true },
  { "code": "#333941", "name": "dark slate", "locked": true },
  { "code": "#6d758d", "name": "slate", "locked": true },
  { "code": "#b3b9d1", "name": "light slate", "locked": true }
];