export const WPLACE_COLORS = [
  { "code": 0x000000, "name": "black", "locked": false },
  { "code": 0x3c3c3c, "name": "dark gray", "locked": false },
  { "code": 0x787878, "name": "gray", "locked": false },
  { "code": 0xd2d2d2, "name": "light gray", "locked": false },
  { "code": 0xffffff, "name": "white", "locked": false },
  { "code": 0x600018, "name": "deep red", "locked": false },
  { "code": 0xed1c24, "name": "red", "locked": false },
  { "code": 0xff7f27, "name": "orange", "locked": false },
  { "code": 0xf6aa09, "name": "gold", "locked": false },
  { "code": 0xf9dd3b, "name": "yellow", "locked": false },
  { "code": 0xfffabc, "name": "light yellow", "locked": false },
  { "code": 0x0eb968, "name": "dark green", "locked": false },
  { "code": 0x13e67b, "name": "green", "locked": false },
  { "code": 0x87ff5e, "name": "light green", "locked": false },
  { "code": 0x0c816e, "name": "dark teal", "locked": false },
  { "code": 0x10aea6, "name": "teal", "locked": false },
  { "code": 0x13e1be, "name": "light teal", "locked": false },
  { "code": 0x28509e, "name": "dark blue", "locked": false },
  { "code": 0x4093e4, "name": "blue", "locked": false },
  { "code": 0x60f7f2, "name": "cyan", "locked": false },
  { "code": 0x6b50f6, "name": "indigo", "locked": false },
  { "code": 0x99b1fb, "name": "light indigo", "locked": false },
  { "code": 0x780c99, "name": "dark purple", "locked": false },
  { "code": 0xaa38b9, "name": "purple", "locked": false },
  { "code": 0xe09ff9, "name": "light purple", "locked": false },
  { "code": 0xcb007a, "name": "dark pink", "locked": false },
  { "code": 0xec1f80, "name": "pink", "locked": false },
  { "code": 0xf38da9, "name": "light pink", "locked": false },
  { "code": 0x684634, "name": "dark brown", "locked": false },
  { "code": 0x95682a, "name": "brown", "locked": false },
  { "code": 0xf8b277, "name": "beige", "locked": false },
  { "code": 0xaaaaaa, "name": "medium gray", "locked": true },
  { "code": 0xa50e1e, "name": "dark red", "locked": true },
  { "code": 0xfa8072, "name": "light red", "locked": true },
  { "code": 0xe45c1a, "name": "dark orange", "locked": true },
  { "code": 0x9c8431, "name": "dark goldenrod", "locked": true },
  { "code": 0xc0a830, "name": "goldenrod", "locked": true },
  { "code": 0xe8d45f, "name": "light goldenrod", "locked": true },
  { "code": 0x4a6b3a, "name": "dark olive", "locked": true },
  { "code": 0x5a944a, "name": "olive", "locked": true },
  { "code": 0x84c573, "name": "light olive", "locked": true },
  { "code": 0x0f799f, "name": "dark cyan", "locked": true },
  { "code": 0xbbfaf2, "name": "light cyan", "locked": true },
  { "code": 0x7cc5fc, "name": "light blue", "locked": true },
  { "code": 0x4d31b8, "name": "dark indigo", "locked": true },
  { "code": 0x4a4284, "name": "dark slate blue", "locked": true },
  { "code": 0x7a71c4, "name": "slate blue", "locked": true },
  { "code": 0xb5aef1, "name": "light slate blue", "locked": true },
  { "code": 0x9b5249, "name": "dark peach", "locked": true },
  { "code": 0xd18078, "name": "peach", "locked": true },
  { "code": 0xfab6a4, "name": "light peach", "locked": true },
  { "code": 0xdba463, "name": "light brown", "locked": true },
  { "code": 0x7b6352, "name": "dark tan", "locked": true },
  { "code": 0x9c846b, "name": "tan", "locked": true },
  { "code": 0xd6b594, "name": "light tan", "locked": true },
  { "code": 0xd18051, "name": "dark beige", "locked": true },
  { "code": 0xffc5a5, "name": "light beige", "locked": true },
  { "code": 0x6d643f, "name": "dark stone", "locked": true },
  { "code": 0x948c6b, "name": "stone", "locked": true },
  { "code": 0xcdc59e, "name": "light stone", "locked": true },
  { "code": 0x333941, "name": "dark slate", "locked": true },
  { "code": 0x6d758d, "name": "slate", "locked": true },
  { "code": 0xb3b9d1, "name": "light slate", "locked": true }
];